services:
    _defaults:
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    Pulse\ExceptionBundle\:
        resource: '../../'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Repository,Tests}'

    Pulse\ExceptionBundle\Exception\PulseExceptionRegistry:
        arguments:
            - !tagged pulse_exception.handler
    
    Pulse\ExceptionBundle\Handler\Pulse\PulseGeneraleLoggerExceptionHandler:
        decorates: 'Pulse\ExceptionBundle\Handler\Pulse\PulseGeneraleExceptionHandler'
        arguments: ['@.inner', '@logger']
        decoration_priority: 1
        public: false

    Pulse\ExceptionBundle\Listener\PulseExceptionListener:
        tags: 
            - { name: kernel.event_listener, priority: 200}

    Pulse\ExceptionBundle\Listener\FormatRequestListener:
        tags: 
            - { name: kernel.event_listener, priority: 300}
